### ISSUE TITLE
cant build shared library 

### ISSUE THREAD

**Issue by metux** [unicode-rs/unicode-xid#6]
make[1]: Entering directory '/home/nekrad/src/cargo/unicode-xid'
/home/nekrad/.usr/rust/bin/rustc src/lib.rs --crate-type=dylib --crate-name unicode_xid -o libunicode_xid.so.0.1.0
error: language item required, but not found: `panic_fmt`

error: language item required, but not found: `eh_personality`

error: aborting due to 2 previous errors

**Comment by metux** [comment]
Seems to come from this:
#![no_std]

Is that necessary ?

**Comment by SimonSapin** [comment]
`#![no_std]` allows this library to be used in platforms that don’t have a full standard library, for example on embedded systems without an operating system. Programs on such systems need to define their own handling of panics.

Programs that don’t care about that will normally have some other crate that does depend on `std` (which defines these language items).

Why do you want this crate by itself as a shared library, rather than make your own crate that depends on it? Also, is there a reason not to use Cargo?

**Comment by crazyboycjr** [comment]
> Why do you want this crate by itself as a shared library, rather than make your own crate that depends on it?

Hi, @SimonSapin, I may have a use case for that. I'm having a diamond dependency issue where I'm thinking that compiling all transitive dependent crates as dylib could help (at least in this particular case). I have uploaded the simple demo to this [repo](https://bitbucket.org/crazyboycjr/diamond/src/demo/) (for reproducing). The code contains 3 crates, libb, libc, and libd.
```
     nix.rlib
     /      \
  libb.so  libc.so
     \      /
     libd.so
```

With the code basically looks like this.
```
$ grep -r . src/
src/libb/src/lib.rs:use nix::sys::mman;
src/libb/Cargo.toml:[package]
src/libb/Cargo.toml:name = "libb"
src/libb/Cargo.toml:version = "0.1.0"
src/libb/Cargo.toml:edition = "2021"
src/libb/Cargo.toml:# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
src/libb/Cargo.toml:[lib]
src/libb/Cargo.toml:crate-type = ["dylib"]
src/libb/Cargo.toml:[dependencies]
src/libb/Cargo.toml:nix = { version = "0.25.0", default-features = false, features = ["mman"] }
src/libc/src/lib.rs:use nix::sys::stat;
src/libc/Cargo.toml:[package]
src/libc/Cargo.toml:name = "libc"
src/libc/Cargo.toml:version = "0.1.0"
src/libc/Cargo.toml:edition = "2021"
src/libc/Cargo.toml:# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
src/libc/Cargo.toml:[lib]
src/libc/Cargo.toml:crate-type = ["dylib"]
src/libc/Cargo.toml:[dependencies]
src/libc/Cargo.toml:nix = { version = "0.25.0", default-features = false, features = ["fs"] }
src/libd/src/lib.rs:use libb;
src/libd/src/lib.rs:use libc;
src/libd/Cargo.toml:[package]
src/libd/Cargo.toml:name = "libd"
src/libd/Cargo.toml:version = "0.1.0"
src/libd/Cargo.toml:edition = "2021"
src/libd/Cargo.toml:# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
src/libd/Cargo.toml:[lib]
src/libd/Cargo.toml:crate-type = ["dylib"]
src/libd/Cargo.toml:[dependencies]
src/libd/Cargo.toml:libb = { path = "../libb" }
src/libd/Cargo.toml:libc = { path = "../libc" }
```

This however throws me an error, which seems to be expected.
```
error: cannot satisfy dependencies so `nix` only shows up once
  |
  = help: having upstream crates all available in one format will likely make this go away
```

This is, of course, just for a demo of a more complex plugin system I'm currently building. One seemly promising workaround for me would be to customize cargo and build a dylib for every transitive dependency. So I'm starting from the well-known `bitflags` (which `nix` crate depends on) crate and attempting to make it generate a dylib. `bitflags` is a no_std crate with only macros declared. Adding `eh_personality` and `panic_handlers` for it compiles the crate and gives me a `libbitflags.so` but stops me from linking a normal library/binary with it because of duplicate language items.

**Comment by Manishearth** [comment]
Rust ... really isn't designed to be built as a bunch of dylibs, the Rust ABI doesn't work that way and this is very much unsupported.

This isn't really an issue with this crate, y'all are having an issue with Rust's model not being suited for your particular choice of solution.

If you want to build Rust dylibs you typically need a shim crate that defines these things.

**Comment by crazyboycjr** [comment]
Hi @Manishearth. Thanks for your explanation! Very much agree that this isn't the issue of unicode-rs. Just have one last quick follow-up question.

> Rust ... really isn't designed to be built as a bunch of dylibs, the Rust ABI doesn't work that way and this is very much unsupported.

I have seen this many places elsewhere but have not seen any further discussion. In my (as well as many others) particular case, I can ensure the compiler toolchains are the exact same version, does that work around this ABI compatibility issue, or there are actually any other hidden pitfalls that I am not aware of (even though these dylibs are generated using the same compiler)?
